### ISSUE TITLE
Épico - Criar Estrutura idêntica à Planilha

### ISSUE THREAD

**Issue by gabrielsimas** [gabrielsimas/simasoft-finance#4]
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095054
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095245
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095233
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095579
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095602
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095679
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095772
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095695
- [ ] https://github.com/gabrielsimas/simasoft-finance/projects/1#card-74095714

**Comment by gabrielsimas** [comment]
Separar este Épico em User Stories e colocar no Board
